baseurl = "/"
title = "ThiRsty Day"
theme = "hugo-theme-cleanwhite"
languageCode = "ko-kr"
# Enable comments by entering your Disqus shortname
disqusShortname = "ksone"
googleAnalytics = "UA-131114985-2"
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
hasCJKLanguage = true



ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]


[outputs]
  home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "img/background.webp"
  SEOTitle = "Thirsty Day | ksone blog"
  description = "R언어 프로그래밍, 읽고 보고 기록"
  keyword = "R, Sangwonkim, 프로그래밍, 통계, 머신러닝, 딥러닝"
  slogan = "Pay it foward"

  image_404 = "img/404-bg.jpg"
  title_404 = "찾을 수 없는 파일입니다. 404 :("
  google-site-verification = "l2RrHpNRHyo7d-ADhOctFkmd4hYiAZXmFzbm80eu8-g"
  naver-site-verification = "860f10f87caf5320a535f1d9c4811ec284b4c120"
  



  # Sidebar settings
  sidebar_about_description = "Looking for job, Open Source Enthusiast and Life Adventurer"
  #sidebar_avatar  # use absolute URL, seeing it's used in both `/` and `/about/`
  sidebar_avatar = "img/바다.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true 
  featured_condition_size = 1 

  
  # We need a proxy to access Disqus api in China
  # Follow https://github.com/zhaohuabing/disqus-php-api to set up your own disqus proxy
  disqus_proxy = ""
  disqus_site = ""


  # Include any custom CSS and/or JS files, url or relative to /static folder
  #custom_css = ["css/lightbox.css", "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css", "css/main.css"]
  #custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js"]

  # Highlight.js theme 코드보여지는 형식들
  # demo: https://highlightjs.org/static/demo/
  highlightjs = "hybrid"

  [params.social]
  rss            = true 
  email          = "kimsw561@gmail.com"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  #twitter       = "full profile url in twitter"
  linkedin       = "/"
  stackoverflow  = "https://stackoverflow.com/users/9857061/sang-won-kim"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/KS-one"
#  medium         = "full profile url in medium"
  #pinterest     = "full profile url in pinterest"
  #reddit        = "full profile url in reddit"
  #gitlab        = "full profile url in gitlab"
  #mastodon      = "full profile url in mastodon"
  #keybase       = "full profile url in keybase"
  #git           = "full profile url for git user"
  
 # [[params.friend_link]]
  #title = "이름"
  #href =  "주소"

  #[[params.bookmark_link]]
  #title =  "Martin Fowler"
  #href =  "https://martinfowler.com"
  #[[params.bookmark_link]]
  #title = "ServiceMesher"
  #href =  "http://www.servicemesher.com"
  #[[params.bookmark_link]]
  #title =  "Pxhere"
  #href = "https://pxhere.com"
  #[[params.bookmark_link]]
  #title = "unsplash"
  #href = "https://unsplash.com"


  #[[params.addtional_menus]]
  #title =  "ABOUT"
  #href =  "/about/"
  #weight = 6

[outputFormats.Algolia]
baseName = "4M5FQ34CQH"
isPlainText = true
mediaType = "application/json"
notAlternative = true
  
[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 

enableRobotsTXT = true

[sitemap]
changefreq = "hourly"
filename = "sitemap.xml"
priority = 0.5